# for docker compose
FROM node:10

WORKDIR /usr/src/app/social

COPY package*.json ./
COPY . .

RUN npm install -g @angular/cli @angular-devkit/build-angular && npm install

EXPOSE 4200

CMD ["npm", "start"]