name: Front-end tests

on: 
  pull_request:
    paths:
       - 'social/**'

     

defaults:
  run:
    working-directory: ./social

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js to test
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    # - run: npm run build --if-present
    - run: npm test

